# Generated by Django 3.2.9 on 2022-10-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emmployee_name',
            new_name='employee_name',
        ),
    ]
