# Generated by Django 3.2.9 on 2022-10-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_emmployee_name_employee_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.IntegerField(null=True),
        ),
    ]
